"""add_new_ml_columns

Revision ID: 0b885c5cbb43
Revises: 
Create Date: 2026-02-23 15:56:06.680772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b885c5cbb43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('headmotion_score', sa.Float(), nullable=True))
    op.add_column('analysis_results', sa.Column('confidence_calibrated_probability', sa.Float(), nullable=True))
    op.add_column('analysis_results', sa.Column('uncertainty_flag', sa.String(length=8), nullable=True))
    op.add_column('analysis_results', sa.Column('entropy', sa.Float(), nullable=True))
    op.add_column('analysis_results', sa.Column('explanation', sa.String(length=512), nullable=True))
    op.add_column('analysis_results', sa.Column('modality_weights', sa.JSON(), nullable=True))
    op.add_column('analysis_results', sa.Column('fusion_method', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'fusion_method')
    op.drop_column('analysis_results', 'modality_weights')
    op.drop_column('analysis_results', 'explanation')
    op.drop_column('analysis_results', 'entropy')
    op.drop_column('analysis_results', 'uncertainty_flag')
    op.drop_column('analysis_results', 'confidence_calibrated_probability')
    op.drop_column('analysis_results', 'headmotion_score')
    # ### end Alembic commands ###
